name: Daily Tagtaly Charts

on:
  schedule:
    # Run at 7 AM UTC every day
    - cron: '0 7 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m textblob.download_corpora

    - name: Run Tagtaly pipeline
      run: |
        python main_pipeline.py

    - name: Upload charts as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: daily-charts-${{ github.run_number }}
        path: |
          viral_charts_*/*.png
          viral_charts_*/*.txt
        retention-days: 30

    - name: Commit database updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Tagtaly Bot"
        git add uk_news.db
        git diff --quiet && git diff --staged --quiet || git commit -m "Update database - $(date +'%Y-%m-%d')"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
