name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tagtaly pipeline
        run: cd src && python main_pipeline.py

      - name: Create index.html
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Tagtaly - News Analytics</title>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0e27; color: #fff; line-height: 1.6; }
                  .container { max-width: 1200px; margin: 0 auto; padding: 40px 20px; }
                  header { text-align: center; margin-bottom: 50px; border-bottom: 1px solid #1e2749; padding-bottom: 30px; }
                  h1 { font-size: 2.5em; color: #00d4ff; margin-bottom: 10px; }
                  .subtitle { font-size: 1.1em; color: #a0aec0; }
                  .info-box { background: #1a202c; border-left: 4px solid #00d4ff; padding: 20px; margin: 20px 0; border-radius: 4px; }
                  .footer { text-align: center; margin-top: 50px; padding-top: 30px; border-top: 1px solid #1e2749; color: #718096; }
                  a { color: #00d4ff; text-decoration: none; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <div class="container">
                  <header>
                      <h1>📊 Tagtaly</h1>
                      <p class="subtitle">News That Matters. Data That Shows It.</p>
                  </header>

                  <div class="info-box">
                      <h2>Latest Viral Chart Analysis</h2>
                      <p>Automated analysis of 500+ daily articles from UK & US news sources. Topics detected: surge alerts, political mentions, sentiment shifts, record highlights, and media bias.</p>
                  </div>

                  <div class="info-box">
                      <h3>📈 Sources</h3>
                      <p>BBC • Guardian • Sky News • Telegraph • Independent • CNN • NY Times • Washington Post • Reuters • AP News</p>
                  </div>

                  <div class="info-box">
                      <h3>🔄 Update Schedule</h3>
                      <p>Charts generated daily at 7 AM UTC</p>
                  </div>

                  <div class="footer">
                      <p><a href="https://github.com/Mxgrig/tagtaly">🔗 View Source Code on GitHub</a></p>
                      <p style="margin-top: 20px; font-size: 0.9em;">Powered by Python • Matplotlib • TextBlob</p>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Push to public repo
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/Mxgrig/tagtaly-pages.git deploy
          cp index.html deploy/
          cp -r output/* deploy/ 2>/dev/null || true
          cd deploy
          git config user.name "Tagtaly Bot"
          git config user.email "bot@tagtaly.dev"
          git add -A
          git commit -m "Update: Generated charts $(date +%Y-%m-%d)" || echo "No changes"
          git push
